### ISSUE TITLE
Always getting AccessDeniedException when trying to use copy or hardlink

### ISSUE THREAD

**Issue by elbasan** [jlesage/docker-filebot#1]
![image](https://user-images.githubusercontent.com/12799363/41202042-c0aaae30-6cc3-11e8-8c1c-b5e381abba19.png)

I've also tried installing docker-filebot as a user or root, even UMASK=000 didnt help
```
docker run -d \
    --name=filebot \
    -p 5800:5800 \
    -v /docker/appdata/filebot:/config:rw \
    -v /media:/storage:rw \
    jlesage/filebot
```
Log:
```
AccessDeniedException: /storage/plex/Movies/Final Destination (2000)
java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /storage/plex/Movies/Final Destination (2000)
        at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
        at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:324)
        at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.nio.file.AccessDeniedException: /storage/plex/Movies/Final Destination (2000)
        at net.filebot.util.FileUtilities.resolveDestination(FileUtilities.java:116)
        at net.filebot.util.FileUtilities.copyAs(FileUtilities.java:90)
        at net.filebot.StandardRenameAction$2.rename(StandardRenameAction.java:30)
        at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:249)
        at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:222)
        at net.filebot.util.ui.ProgressMonitor$1.call(ProgressMonitor.java:27)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
```

**Comment by jlesage** [comment]
Is `/media` on the host a network share?

**Comment by hazyitsm** [comment]
Apologies if this is inappropriate hijacking of the thread, but I have a similar issue. I'd be happy to open a new issue is that is more appropriate. Here is my log:

> AccessDeniedException: /storage/TV/MASH/Season 1/MASH - 01x01 - MASH the Pilot.m4v -> /storage/TV/MASH/Season 1/MASH - 1x01 - MASH the Pilot.m4v,
java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /storage/TV/MASH/Season 1/MASH - 01x01 - MASH the Pilot.m4v -> /storage/TV/MASH/Season 1/MASH - 1x01 - MASH the Pilot.m4v,
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:111),
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:337),
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:77),
Caused by: java.nio.file.AccessDeniedException: /storage/TV/MASH/Season 1/MASH - 01x01 - MASH the Pilot.m4v -> /storage/TV/MASH/Season 1/MASH - 1x01 - MASH the Pilot.m4v,
	at net.filebot.util.FileUtilities.moveRename(FileUtilities.java:89),
	at net.filebot.StandardRenameAction$1.rename(StandardRenameAction.java:25),
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:315),
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:288),
	at net.filebot.util.ui.ProgressMonitor$1.call(ProgressMonitor.java:27),
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423),

I have the /storage volume mapped to an external folder mounted as /mnt/nas_media, as shown in the screen shot. The mount on the host server has full permissions to the external folder.

![Screenshot 2019-08-12 at 9 29 03 PM](https://user-images.githubusercontent.com/51681019/62911063-8a792180-bd48-11e9-953a-65d73562dc2c.png)

**Comment by jlesage** [comment]
So `/mnt/nas_media` has full permission, but when you mapped the folder to `/storage` in the container, did you set read/write permission?  If you are unsure, you can provide the output of `docker inspect <name of the container>`.

**Comment by hazyitsm** [comment]
I got it figured out. Turns out that my default account didn't have access to the network share. I fixed that and I'm good now. Thank you!

**Comment by jlesage** [comment]
Perfect!
