### ISSUE TITLE
Getting an access denied error when renaming files

### ISSUE THREAD

**Issue by pbarone** [jlesage/docker-filebot#80]
When trying to rename files I get the below error:

AccessDeniedException: /War Machine (2017)
java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /War Machine (2017)
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:324)
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.nio.file.AccessDeniedException: /War Machine (2017)
	at net.filebot.util.FileUtilities.resolveDestination(FileUtilities.java:116)
	at net.filebot.util.FileUtilities.moveRename(FileUtilities.java:61)
	at net.filebot.StandardRenameAction$1.rename(StandardRenameAction.java:22)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:249)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:222)
	at net.filebot.util.ui.ProgressMonitor$1.call(ProgressMonitor.java:27)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
AccessDeniedException: /War Machine (2017)
java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: /War Machine (2017)
	at net.filebot.ui.rename.RenameAction.lambda$actionPerformed$1(RenameAction.java:91)
	at net.filebot.util.ui.SwingUI.withWaitCursor(SwingUI.java:324)
	at net.filebot.ui.rename.RenameAction.actionPerformed(RenameAction.java:69)
Caused by: java.nio.file.AccessDeniedException: /War Machine (2017)
	at net.filebot.util.FileUtilities.resolveDestination(FileUtilities.java:116)
	at net.filebot.util.FileUtilities.moveRename(FileUtilities.java:61)
	at net.filebot.StandardRenameAction$1.rename(StandardRenameAction.java:22)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:249)
	at net.filebot.ui.rename.RenameAction$StandardRenameWorker.call(RenameAction.java:222)
	at net.filebot.util.ui.ProgressMonitor$1.call(ProgressMonitor.java:27)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)

I tried running the container with PUID and PGID = 0 as well but still nothing. Any idea?

**Comment by jlesage** [comment]
It's the `USER_ID` and `GROUP_ID` environment variables that need to be adjusted (not `PUID`/`PGID`).  See https://github.com/jlesage/docker-filebot#environment-variables

**Comment by pbarone** [comment]
My bad! In the format I was pointing to / instead of my /storage directory!
